#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ghost-self-growth-loop.sh [--owner OWNER] [--repo REPO] [--visibility public|private] [--execute]
  ghost-self-growth-loop.sh --dry-run [--owner OWNER] [--repo REPO]

Description:
  Creates a local repo workspace at ~/repos/github.com/<OWNER>/<REPO>,
  adds a minimal starter README/TODO, commits changes, and (optionally)
  creates/pushes a GitHub repository via gh CLI.

Options:
  --owner       GitHub owner (default: value from GH_OWNER or git config user.name)
  --repo        Repository name (default: ghost-growth-YYYYMMDD)
  --visibility  public or private (default: public)
  --execute     Actually run commands that modify local/remote state
  --dry-run     Print planned commands only (default mode)
EOF
}

OWNER="${GH_OWNER:-${GITHUB_OWNER:-$(git config --global github.user 2>/dev/null || true)}}"
OWNER="${OWNER:-jungju}"
TODAY="$(date +%Y%m%d)"
REPO="ghost-growth-${TODAY}"
VISIBILITY="public"
EXECUTE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner) OWNER="${2:-}"; shift 2 ;;
    --repo) REPO="${2:-}"; shift 2 ;;
    --visibility) VISIBILITY="${2:-}"; shift 2 ;;
    --execute) EXECUTE=1; shift ;;
    --dry-run) EXECUTE=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "${OWNER}" || -z "${REPO}" ]]; then
  echo "owner/repo must not be empty" >&2
  exit 1
fi
if [[ "${VISIBILITY}" != "public" && "${VISIBILITY}" != "private" ]]; then
  echo "visibility must be public or private" >&2
  exit 1
fi

DEST="${HOME}/repos/github.com/${OWNER}/${REPO}"

run() {
  if [[ "${EXECUTE}" -eq 1 ]]; then
    echo "+ $*"
    "$@"
  else
    echo "[dry-run] $*"
  fi
}

mkdir_if_needed() {
  if [[ -d "$1" ]]; then
    return 0
  fi
  run mkdir -p "$1"
}

printf "owner=%s repo=%s visibility=%s mode=%s\n" \
  "${OWNER}" "${REPO}" "${VISIBILITY}" "$([[ "${EXECUTE}" -eq 1 ]] && echo execute || echo dry-run)"

mkdir_if_needed "$(dirname "${DEST}")"

if [[ ! -d "${DEST}/.git" ]]; then
  run mkdir -p "${DEST}"
  run git -C "${DEST}" init -b main
else
  run git -C "${DEST}" fetch --all --prune
fi

if [[ ! -f "${DEST}/README.md" ]]; then
  if [[ "${EXECUTE}" -eq 1 ]]; then
    cat > "${DEST}/README.md" <<EOF
# ${REPO}

This repository is generated by jgo self-growth loop.

## Goal
- Build small, real, public artifacts continuously.
EOF
    echo "+ write ${DEST}/README.md"
  else
    echo "[dry-run] write ${DEST}/README.md"
  fi
fi

if [[ ! -f "${DEST}/TODO.md" ]]; then
  if [[ "${EXECUTE}" -eq 1 ]]; then
    cat > "${DEST}/TODO.md" <<'EOF'
# TODO
- [ ] Define first shippable feature
- [ ] Implement minimal code
- [ ] Add one test
- [ ] Publish release note
EOF
    echo "+ write ${DEST}/TODO.md"
  else
    echo "[dry-run] write ${DEST}/TODO.md"
  fi
fi

if [[ "${EXECUTE}" -eq 1 ]]; then
  if [[ -n "$(git -C "${DEST}" status --porcelain)" ]]; then
    git -C "${DEST}" add README.md TODO.md
    git -C "${DEST}" commit -m "chore: bootstrap self-growth repository"
  fi
else
  echo "[dry-run] git -C ${DEST} add README.md TODO.md"
  echo "[dry-run] git -C ${DEST} commit -m 'chore: bootstrap self-growth repository'"
fi

if command -v gh >/dev/null 2>&1; then
  if [[ "${EXECUTE}" -eq 1 ]]; then
    if gh repo view "${OWNER}/${REPO}" >/dev/null 2>&1; then
      echo "remote repo exists: ${OWNER}/${REPO}"
    else
      gh repo create "${OWNER}/${REPO}" "--${VISIBILITY}" --source "${DEST}" --remote origin --push
    fi
    run git -C "${DEST}" push -u origin main
  else
    echo "[dry-run] gh repo view ${OWNER}/${REPO}"
    echo "[dry-run] gh repo create ${OWNER}/${REPO} --${VISIBILITY} --source ${DEST} --remote origin --push"
    echo "[dry-run] git -C ${DEST} push -u origin main"
  fi
else
  echo "gh not found; skipped remote repository creation"
fi

echo "done"
